from typing import Optional
from pydantic import BaseModel, ConfigDict, EmailStr, Field, field_validator


class ContactRequest(BaseModel):
    """
    Validation schema for contact form requests arriving at POST /api/contact.
    Validates email format, trims whitespace, enforces non-empty fields, and checks character limits.
    """

    name: str = Field(
        ..., min_length=1, max_length=100, description="Full name of the sender"
    )
    email: EmailStr = Field(..., description="Valid email address of the sender")
    subject: str = Field(
        ...,
        min_length=1,
        max_length=200,
        description="Subject line of the contact message",
    )
    message: str = Field(
        ...,
        min_length=1,
        max_length=5000,
        description="Message content (max 5000 characters)",
    )
    recaptchaToken: Optional[str] = Field(
        default=None,
        alias="recaptchaToken",
        description="Optional Google reCAPTCHA token generated by the frontend",
    )

    model_config = ConfigDict(
        str_strip_whitespace=True,
        populate_by_name=True,
        json_schema_extra={
            "example": {
                "name": "Jane Doe",
                "email": "jane.doe@example.com",
                "subject": "Project Inquiry",
                "message": "Hi, I would like to discuss a potential collaboration on a new project!",
            }
        },
    )

    @field_validator("name", "subject", "message", "recaptchaToken", mode="after")
    @classmethod
    def reject_empty_or_whitespace_only(cls, value: Optional[str]) -> Optional[str]:
        """
        Ensures string fields do not consist solely of whitespace after stripping.
        """
        if value is None:
            return value
        stripped = value.strip()
        if not stripped:
            raise ValueError("Field cannot be empty or consist solely of whitespace.")
        return stripped


class StatusResponse(BaseModel):
    """Response schema for GET / root status check."""

    status: str = "running"


class HealthResponse(BaseModel):
    """Response schema for GET /health uptime check."""

    success: bool = True


class ContactResponse(BaseModel):
    """Response schema for POST /api/contact form submission."""

    success: bool
    message: str
